# Generated by Django 5.0.3 on 2024-03-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlıq')),
                ('anons', models.CharField(max_length=255, verbose_name='Xülasə')),
                ('full_text', models.TextField(verbose_name='Mətn')),
                ('date', models.DateField(verbose_name='Nəşr tarixi')),
            ],
        ),
    ]
