# Generated by Django 5.0.3 on 2024-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Adi məsəslə'), (1, 'Təcili məsəslə'), (2, 'Çox vacib'), (3, 'Başqa')], default=0, verbose_name='İşin vacibliyi'),
        ),
    ]
