# Generated by Django 4.2.11 on 2024-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0002_articles_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Reyasət', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
    ]
