# Generated by Django 4.2.11 on 2024-04-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0003_division_alter_articles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index_main.division')),
            ],
        ),
    ]
