# Generated by Django 4.2.11 on 2024-04-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0006_alter_department_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('current', 'Current'), ('former', 'Former')], max_length=10)),
                ('employee_type', models.CharField(choices=[('ordinary', 'Ordinary'), ('scientific', 'Scientific')], max_length=10)),
                ('degree', models.CharField(blank=True, choices=[('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine'), ('JD', 'Doctor of Jurisprudence'), ('PhD Literature', 'Doctor of Philosophy in Literature')], max_length=100, null=True)),
                ('academic_rank', models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('associate', 'Associate Professor'), ('professor', 'Professor'), ('corresponding_member', 'Corresponding Member'), ('academician', 'Academician')], max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_main.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_main.employee')),
            ],
        ),
    ]
