# Generated by Django 4.2.11 on 2024-04-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0007_employee_employmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
