# Generated by Django 4.2.11 on 2024-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0009_phonenumber_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='position',
            field=models.CharField(choices=[('Şöbə müdiri', 'Şöbə müdiri'), ('Mühəndis', 'Mühəndis'), ('Proqramlaşdırıcı-mühəndis', 'Proqramlaşdırıcı-mühəndis'), ('elmi işçi', 'elmi işçi')], default='elmi işçi', max_length=100, null=True),
        ),
    ]
