# Generated by Django 4.2.11 on 2024-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0010_alter_department_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Şöbə', 'verbose_name_plural': 'Şöbələr'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Bölmə', 'verbose_name_plural': 'Bölmələr'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'İşçi', 'verbose_name_plural': 'İşçilər'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'İşçi tarixçəsi', 'verbose_name_plural': 'İşçi tarixçələri'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'İnstitut', 'verbose_name_plural': 'İnstitutlar'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ata adı'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.CharField(choices=[('Şöbə müdiri', 'Şöbə müdiri'), ('Mühəndis', 'Mühəndis'), ('Proqr.-mühəndis', 'Proqramlaşdırıcı-mühəndis'), ('elmi işçi', 'elmi işçi')], default='elmi işçi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('associate', 'Associate Professor'), ('professor', 'Professor'), ('corresponding_member', 'Corresponding Member'), ('academician', 'Academician')], max_length=100, null=True, verbose_name='Akademik ranq'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Doğum tarixi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine'), ('JD', 'Doctor of Jurisprudence'), ('PhD Literature', 'Doctor of Philosophy in Literature')], max_length=100, null=True, verbose_name='Dərəcə'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('ordinary', 'işçi'), ('scientific', 'elmi işçi')], max_length=10, verbose_name='İşçinin tipi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='AMEA da işə başlama tarixi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('current', 'indiki'), ('former', 'keçmiş')], max_length=10),
        ),
    ]
