# Generated by Django 4.2.11 on 2024-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0011_alter_department_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine'), ('JD', 'Doctor of Jurisprudence'), ('PhD Literature', 'Doctor of Philosophy in Literature'), ('filologiya elmləri doktoru', 'filologiya elmləri doktoru')], max_length=100, null=True, verbose_name='Dərəcə'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_year',
            field=models.DateField(blank=True, default='h/h', null=True, verbose_name='bitirmə tarixi'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='əsas iş'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_year',
            field=models.DateField(verbose_name='başlama tarixi'),
        ),
    ]
