# Generated by Django 4.2.11 on 2024-04-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0012_alter_employee_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'İş yeri', 'verbose_name_plural': 'İş yerləri'},
        ),
    ]
