# Generated by Django 4.2.11 on 2024-04-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0013_alter_employmenthistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('profile_url', models.URLField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('data', models.JSONField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_main.profile')),
            ],
        ),
    ]
