# Generated by Django 5.0.4 on 2024-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_main', '0015_alter_division_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(choices=[('Google Scholar', 'Google Scholar'), ('WOS', 'Web of Science'), ('Scopus', 'Scopus'), ('ResearchGate', 'ResearchGate'), ('ACADEMIA', 'ACADEMIA'), ('TRIndex', 'TRIndex'), ('Orcid', 'Orcid')], max_length=15, verbose_name='Platforma'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_url',
            field=models.URLField(verbose_name='Profil url'),
        ),
    ]
